//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_ChemistShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineOrder
    {
        public int OrderId { get; set; }
        public int MedicineId { get; set; }
        public int ProductCount { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Order Order { get; set; }
    }
}
