//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_ChemistShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.MedicineOrder = new HashSet<MedicineOrder>();
        }
    
        public int MedicineId { get; set; }
        public int MedicineManufacturerId { get; set; }
        public string MedicineName { get; set; }
        public double MedicineCost { get; set; }
        public double MedicineDiscount { get; set; }
        public double MedicineDiscountMax { get; set; }
        public double MedicineRank { get; set; }
        public int MedicineCount { get; set; }
        public int MedicineCategory { get; set; }
        public System.DateTime MedicineDateManufacturing { get; set; }
        public int MedicineExpirationDate { get; set; }
        public string MedicineDescription { get; set; }
        public string MedicinePhoto { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineOrder> MedicineOrder { get; set; }
    }
}
